Added validation for base and head being the same thing.  Fixed a bug when initiating a pull request to and from repos from owners other than the currently configured user for GITHUB_LOGIN.
Needed to not be here at all

diff --git a/pullmyfinger b/pullmyfinger
--- a/pullmyfinger
+++ b/pullmyfinger
@@ -88,11 +88,29 @@ __pmf_github_get_api_url() {
     echo "https://api.github.com/repos/${github_user}/${project}/${request_type}"
 }
 
+__pmf_validate_git_ref_exists() {
+    local return_code git_ref
+    git_ref=$1
+    return_code=0
+
+    # Validate the argument is a valid git-ref
+    if ! \git rev-parse --verify --quiet "${git_ref}" > /dev/null
+    then
+        echo "ERROR => The target (base) branch \"${git_ref}\" could not be verified as a valid git reference..."
+        return_code=1
+    fi
+
+    return ${return_code}
+}
+
 __pmf_github_create_pull_request() {
-    local return_code target_branch head_branch source_branch command script_arg commit_message milestone remote_name remote_true_name
-    local github_output github_api_url error_message github_url pull_request_number milestone_number payload
+    local return_code command script_arg commit_message \
+          base_branch base_remote_alias base_remote_true_name \
+          head_branch head_remote_alias head_remote_true_name \
+          github_output github_api_url github_url github_pull_request_number github_error_message github_pull_request_payload
+
     return_code=1
-    target_branch=$1
+    base_branch=$1
 
     for script_arg in "$@";
     do
@@ -102,7 +120,7 @@ __pmf_github_create_pull_request() {
         case "${command}" in
             base)
                 shift
-                target_branch=$1
+                base_branch=$1
                 shift
             ;;
             head)
@@ -113,54 +131,70 @@ __pmf_github_create_pull_request() {
         esac
     done;
 
-    # Validate argument exists
-    [[ -z "${target_branch}" ]] && { echo "ERROR => Could not determine target branch for pull request..."; return ${return_code}; }
-    
     # Validate the argument is a branch
-    if ! \git rev-parse --verify --quiet "${target_branch}" > /dev/null
+    if ! __pmf_validate_git_ref_exists "${base_branch}"
     then
-        echo "ERROR => The target/base branch \"${target_branch}\" could not be verified as a valid git reference..."
-        return ${return_code}
-    else
-        target_branch=$(\git rev-parse --symbolic-full-name ${target_branch})
+        return $?
     fi
 
     if [[ -z ${head_branch} ]]
     then
         # Get the symbolic name for the branch we are currently on (this is the most common usage)
         head_branch="$(\git symbolic-ref HEAD 2>/dev/null)"
+        # remove refs/heads/ from the branch name
+        head_branch="${head_branch#refs/heads/}"
+        head_remote_alias="${GITHUB_LOGIN}"
+        head_remote_true_name="${GITHUB_LOGIN}"
+    else
+        # Validate the argument is a branch
+        if ! __pmf_validate_git_ref_exists "${head_branch}"
+        then
+            return $?
+        fi
+
+        # We need to get the repo alias name from the head branch argument
+        head_remote_alias="${head_branch%%/*}"
+        head_remote_true_name=$(__pmf_github_get_github_user ${head_remote_alias})
+        # Strip the remote off the head_branch
+        head_branch="${head_branch#*/}"
     fi
 
     # Get the last commit message from the branch we are using as the head branch
-    commit_message=$(\git show -s --format=%s ${head_branch} | sed -e 's/"//g')
+    commit_message=$(\git show -s --format=%s "${head_remote_alias}/${head_branch}" | sed -e 's/"//g')
 
-    # Strip the refs/remotes from the symbolic full name of the target
-    target_branch="${target_branch#refs/remotes/}"
-    base_branch="${target_branch#*/}"
-    remote_name="${target_branch%/${base_branch}}"
+    # We need to get the repo alias name from the base branch argument
+    base_remote_alias="${base_branch%%/*}"
+    base_remote_true_name=$(__pmf_github_get_github_user ${base_remote_alias})
+    # Strip the remote off the base_branch
+    base_branch="${base_branch#*/}"
 
-    #git remote --verbose | \grep push | cut -d ' ' -f1 | cut -f2
+    # Validate that we aren't trying to make a request from and to the same place
+    if [[ "${base_remote_true_name}/${base_branch}" == "${head_remote_true_name}/${head_branch}" ]]
+    then
+        echo "ERROR => The target (base) and source (head) may not be the same thing..."
+        return 99;
+    fi
 
-    github_api_url=$(__pmf_github_get_api_url ${remote_name} "pulls")
-    remote_true_name=$(__pmf_github_get_github_user ${remote_name})
-    payload="{
-    \"title\": \"Pull request to ${remote_true_name}/${base_branch} from ${GITHUB_LOGIN}/${head_branch#refs/heads/}\",
-    \"body\": \"Please pull these commits into ${remote_true_name}/${base_branch}.  Here is the latest commit message:\n\n*\\\"${commit_message}\\\"*\n\n${PULLMYFINGER_SIGNATURE}\",
-    \"head\": \"${GITHUB_LOGIN}:${head_branch}\",
-    \"base\": \"${base_branch}\"
+    github_api_url=$(__pmf_github_get_api_url ${base_remote_alias} "pulls")
+    github_pull_request_payload="{
+    \"title\": \"Pull request to ${base_remote_true_name}/${base_branch} from ${head_remote_true_name}/${head_branch#refs/heads/}\",
+    \"body\": \"Please pull these commits into ${base_remote_true_name}/${base_branch}.  Here is the latest commit message:\n\n*\\\"${commit_message}\\\"*\n\n${PULLMYFINGER_SIGNATURE}\",
+    \"head\": \"${head_remote_true_name}:${head_branch}\",
+    \"base\": \"${base_remote_true_name}:${base_branch}\"
 }"
     
     echo "Initiating Github API request with the following configuration:"
-    echo "    Base (target) branch   => ${remote_true_name}/${base_branch}"
-    echo "    Head (source) branch   => ${GITHUB_LOGIN}/${head_branch}"
+    echo "    Base (target) branch   => ${base_remote_true_name}/${base_branch}"
+    echo "    Head (source) branch   => ${head_remote_true_name}/${head_branch}"
     echo "    Github Url             => ${github_api_url}"
+
     github_output=$(\curl                           \
         --silent                                    \
         --show-error                                \
         --request POST                              \
         --header "Content-type: application/json"   \
         --user "${GITHUB_LOGIN}:${GITHUB_PASSWORD}" \
-        --data "${payload}"                         \
+        --data "${github_pull_request_payload}"                         \
         ${github_api_url})
 
     if [[ -z "${github_output}" ]]
@@ -168,16 +202,16 @@ __pmf_github_create_pull_request() {
         echo -e "ERROR => Pull request failed to create :( \n\n${github_output}"
     else
         # Now make sure we didn't have an error message returned
-        error_message=$(echo "${github_output}" | \python -c "import json;import sys;obj=json.load(sys.stdin);print obj['message']" 2>/dev/null)
-        if [[ -z ${error_message} ]]
+        github_error_message=$(echo "${github_output}" | \python -c "import json;import sys;obj=json.load(sys.stdin);print obj['message']" 2>/dev/null)
+        if [[ -z ${github_error_message} ]]
         then
             github_url=$(echo "${github_output}" | \python -c "import json;import sys;obj=json.load(sys.stdin);print obj['html_url']")
-            pull_request_number=$(echo "${github_output}" | \python -c "import json;import sys;obj=json.load(sys.stdin);print obj['number']")
-            echo "Pull request ${pull_request_number} was created successfully at ${github_url}"
+            github_pull_request_number=$(echo "${github_output}" | \python -c "import json;import sys;obj=json.load(sys.stdin);print obj['number']")
+            echo "Pull request ${github_pull_request_number} was created successfully at ${github_url}"
             \open ${github_url}
             return_code=0
         else
-            echo -e "\n\nERROR => Pull request failed to create because \"${error_message}\".  Here's the full output =>"
+            echo -e "\n\nERROR => Pull request failed to create because \"${github_error_message}\".  Here's the full output =>"
             echo "${github_output}" | python -m json.tool
         fi
     fi
@@ -346,7 +380,7 @@ __pmf_completion()
     fi
 }
 
-alias pullmyfinger="__pmf_gateway"
+alias pullmyfinger=__pmf_gateway
 complete -F __pmf_completion pullmyfinger
 
 # Also run the completion scripts for any aliases out there
